### ISSUE TITLE
about how long for posture estimation

### ISSUE THREAD

**Issue by andiconda** [youngwoo-yoon/youtube-gesture-dataset#3]
Could you give me some suggestions about usage of CPU or GPU?
1. could I use the laptop with Win10 to do openpose pose estiamtion ? how long do you think?
2. GPU is must for pose estimation?

**Comment by youngwoo-yoon** [comment]
You need a powerful machine with GPUs for OpenPose. It took several weeks to process all image frames in the dataset. 
There is a faster alternative, but you have to modify some code to use this instead of OpenPose.
https://docs.openvinotoolkit.org/latest/_intel_models_human_pose_estimation_0001_description_human_pose_estimation_0001.html
